{% set name = "picmistandard" %}
{% set version = "0.32.0" %}
{% set build = 0 %}
{% set sha256 = "9be7746ceeddf195f9ce5ef07c9bce2fc194a01cf4ba05e3bdda506d2cc5fb96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/picmi-standard/picmi/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - numpy
    - python >=3.6
    - scipy >=1.5

test:
  imports:
    - picmistandard

about:
  home: https://picmi-standard.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: License.txt
  summary: Standard input format for Particle-In-Cell codes

  description: |
    The Particle-In-Cell Modeling Interface (PICMI) standard
    establishes conventions for the naming and structuring of
    input files for Particle-In-Cell simulations.
  dev_url: https://github.com/picmi-standard/picmi

extra:
  recipe-maintainers:
    - ax3l
    - dpgrote
    - RemiLehe
